//
// Created by Antonin Jean on 29/12/2023.
//
#pragma once

#include "../shared/shared.hpp"
#include <glimac/Sphere.hpp>
#include <iostream>
#include <cassert>
#include <vector>

#define COEF_DIAMETRE 7
#define COEF_DISTANCE 30
#define COEF_DIAMETRE_SUN 2
#define DEFAULT_VALUE 1

// diametre des planetes
#define DIAMETRE_SUN 1400000.f
#define DIAMETRE_MERCURE 4879.f
#define DIAMETRE_VENUS 12104.f
#define DIAMETRE_TERRE 12756.f
#define DIAMETRE_MARS 6792.f
#define DIAMETRE_JUPITER 142984.f
#define DIAMETRE_SATURNE 120536.f
#define DIAMETRE_URANUS 51118.f
#define DIAMETRE_NEPTUNE 49528.f
#define DIAMETRE_PLUTON 2376.f
// diametre des satelites
#define DIAMETRE_MOON 3475.f
// mars
#define DIAMETRE_PHOBOS 18.2f
#define DIAMETRE_DEIMOS 10.2f
// jupiter
#define DIAMETRE_CALISTO 4820.f
#define DIAMETRE_GANYMEDE 5262.4f
#define DIAMETRE_EUROPA 3121.6f
#define DIAMETRE_IO 3643.f
// saturne
#define DIAMETRE_MIMAS 416.f
#define DIAMETRE_ENCELADUS 514.f
#define DIAMETRE_TETHYS 1076.f
#define DIAMETRE_DIONE 1126.f
#define DIAMETRE_RHEA 1530.f
#define DIAMETRE_TITAN 5150.f
#define DIAMETRE_HYPERION 360.f
#define DIAMETRE_IAPETUS 1492.f
// uranus
#define DIAMETRE_ARIEL 1160.f
#define DIAMETRE_UMBRIEL 1169.4f
#define DIAMETRE_TITANIA 1577.8f
#define DIAMETRE_OBERON 1522.8f
#define DIAMETRE_MIRANDA 480.f
// neptune
#define DIAMETRE_TRITON 2706.8f
#define DIAMETRE_NERIEDE 340.f
// pluton
#define DIAMETRE_CHARON 1212.f

#define COEF_DIAMETRE_MERCURE (DIAMETRE_MERCURE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_VENUS (DIAMETRE_VENUS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TERRE (DIAMETRE_TERRE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_MARS (DIAMETRE_MARS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_JUPITER (DIAMETRE_JUPITER / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_SATURNE (DIAMETRE_SATURNE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_URANUS (DIAMETRE_URANUS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_NEPTUNE (DIAMETRE_NEPTUNE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_PLUTON (DIAMETRE_PLUTON / DIAMETRE_SUN) * COEF_DIAMETRE
// diametre des satelites
#define COEF_DIAMETRE_MOON (DIAMETRE_MOON / DIAMETRE_SUN) * COEF_DIAMETRE
// mars
#define COEF_DIAMETRE_PHOBOS (DIAMETRE_PHOBOS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_DEIMOS (DIAMETRE_DEIMOS / DIAMETRE_SUN) * COEF_DIAMETRE
// jupiter
#define COEF_DIAMETRE_CALISTO (DIAMETRE_CALISTO / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_GANYMEDE (DIAMETRE_GANYMEDE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_EUROPA (DIAMETRE_EUROPA / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_IO (DIAMETRE_IO / DIAMETRE_SUN) * COEF_DIAMETRE
// saturne
#define COEF_DIAMETRE_MIMAS (DIAMETRE_MIMAS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_ENCELADUS (DIAMETRE_ENCELADUS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TETHYS (DIAMETRE_TETHYS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_DIONE (DIAMETRE_DIONE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_RHEA (DIAMETRE_RHEA / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TITAN (DIAMETRE_TITAN / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_HYPERION (DIAMETRE_HYPERION / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_IAPETUS (DIAMETRE_IAPETUS / DIAMETRE_SUN) * COEF_DIAMETRE
// uranus
#define COEF_DIAMETRE_ARIEL (DIAMETRE_ARIEL / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_UMBRIEL (DIAMETRE_UMBRIEL / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TITANIA (DIAMETRE_TITANIA / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_OBERON (DIAMETRE_OBERON / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_MIRANDA (DIAMETRE_MIRANDA / DIAMETRE_SUN) * COEF_DIAMETRE
// neptune
#define COEF_DIAMETRE_TRITON (DIAMETRE_TRITON / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_NERIEDE (DIAMETRE_NERIEDE / DIAMETRE_SUN) * COEF_DIAMETRE
// pluton
#define COEF_DIAMETRE_CHARON (DIAMETRE_CHARON / DIAMETRE_SUN) * COEF_DIAMETRE

//////////////////////////////////////////////////////////////////////////////////////////
//DISTANCE PERIHELION
//////////////////////////////////////////////////////////////////////////////////////////

// distance des planetes
#define DISTANCE_SUN 1400000.f
#define DISTANCE_PERIHELION_MERCURE 46000000.f
#define DISTANCE_PERIHELION_VENUS 107500000.f
#define DISTANCE_PERIHELION_TERRE 147100000.f
#define DISTANCE_PERIHELION_MARS 226700000.f
#define DISTANCE_PERIHELION_JUPITER 740600000.f
#define DISTANCE_PERIHELION_SATURNE 1357600000.f
#define DISTANCE_PERIHELION_URANUS 2732700000.f
#define DISTANCE_PERIHELION_NEPTUNE 4471100000.f
#define DISTANCE_PERIHELION_PLUTON 4436800000.f
// distance des satélites
#define DISTANCE_PERIHELION_MOON 363000.f
// mars
#define DISTANCE_PERIHELION_PHOBOS 9378.f
#define DISTANCE_PERIHELION_DEIMOS 23459.f
// jupiter
#define DISTANCE_PERIHELION_CALISTO 1870000.f
#define DISTANCE_PERIHELION_GANYMEDE 1068000.4f
#define DISTANCE_PERIHELION_EUROPA 664000.f
#define DISTANCE_PERIHELION_IO 420000.f
// saturne
#define DISTANCE_PERIHELION_MIMAS 185520.f
#define DISTANCE_PERIHELION_ENCELADUS 238020.f
#define DISTANCE_PERIHELION_TETHYS 294660.f
#define DISTANCE_PERIHELION_DIONE 294660.f
#define DISTANCE_PERIHELION_RHEA 527040.f
#define DISTANCE_PERIHELION_TITAN 1186870.f
#define DISTANCE_PERIHELION_HYPERION 1500930.f
#define DISTANCE_PERIHELION_IAPETUS 3560850.f
// uranus
#define DISTANCE_PERIHELION_ARIEL 190900.f
#define DISTANCE_PERIHELION_UMBRIEL 266000.f
#define DISTANCE_PERIHELION_TITANIA 436300.f
#define DISTANCE_PERIHELION_OBERON 583500.f
#define DISTANCE_PERIHELION_MIRANDA 129900.f
// neptune
#define DISTANCE_PERIHELION_TRITON 354760.f
#define DISTANCE_PERIHELION_NERIEDE 5513400.f
// pluton
#define DISTANCE_PERIHELION_CHARON 19596.f

#define COEF_DISTANCE_PERIHELION_MERCURE (DISTANCE_PERIHELION_MERCURE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_VENUS (DISTANCE_PERIHELION_VENUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_TERRE (DISTANCE_PERIHELION_TERRE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_MARS (DISTANCE_PERIHELION_MARS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_JUPITER (DISTANCE_PERIHELION_JUPITER / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_SATURNE (DISTANCE_PERIHELION_SATURNE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_URANUS (DISTANCE_PERIHELION_URANUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_NEPTUNE (DISTANCE_PERIHELION_NEPTUNE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_PLUTON (DISTANCE_PERIHELION_PLUTON / DISTANCE_SUN) / COEF_DISTANCE
// distance_PERIHELION des satélites
#define COEF_DISTANCE_PERIHELION_MOON (DISTANCE_PERIHELION_MOON / DISTANCE_SUN) / COEF_DISTANCE
// mars
#define COEF_DISTANCE_PERIHELION_PHOBOS (DISTANCE_PERIHELION_PHOBOS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_DEIMOS (DISTANCE_PERIHELION_DEIMOS / DISTANCE_SUN) / COEF_DISTANCE
// jupiter
#define COEF_DISTANCE_PERIHELION_CALISTO (DISTANCE_PERIHELION_CALISTO / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_GANYMEDE (DISTANCE_PERIHELION_GANYMEDE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_EUROPA (DISTANCE_PERIHELION_EUROPA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_IO (DISTANCE_PERIHELION_IO / DISTANCE_SUN) / COEF_DISTANCE
// saturne
#define COEF_DISTANCE_PERIHELION_MIMAS (DISTANCE_PERIHELION_MIMAS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_ENCELADUS (DISTANCE_PERIHELION_ENCELADUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_TETHYS (DISTANCE_PERIHELION_TETHYS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_DIONE (DISTANCE_PERIHELION_DIONE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_RHEA (DISTANCE_PERIHELION_RHEA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_TITAN (DISTANCE_PERIHELION_TITAN / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_HYPERION (DISTANCE_PERIHELION_HYPERION / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_IAPETUS (DISTANCE_PERIHELION_IAPETUS / DISTANCE_SUN) / COEF_DISTANCE
// uranus
#define COEF_DISTANCE_PERIHELION_ARIEL (DISTANCE_PERIHELION_ARIEL / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_UMBRIEL (DISTANCE_PERIHELION_UMBRIEL / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_TITANIA (DISTANCE_PERIHELION_TITANIA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_OBERON (DISTANCE_PERIHELION_OBERON / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_MIRANDA (DISTANCE_PERIHELION_MIRANDA / DISTANCE_SUN) / COEF_DISTANCE
// neptune
#define COEF_DISTANCE_PERIHELION_TRITON (DISTANCE_PERIHELION_TRITON / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PERIHELION_NERIEDE (DISTANCE_PERIHELION_NERIEDE / DISTANCE_SUN) / COEF_DISTANCE
// pluton
#define COEF_DISTANCE_PERIHELION_CHARON (DISTANCE_PERIHELION_CHARON / DISTANCE_SUN) / COEF_DISTANCE

//////////////////////////////////////////////////////////////////////////////////////////
//DISTANCE APHELION
//////////////////////////////////////////////////////////////////////////////////////////

// distance des planetes
#define DISTANCE_APHELION_MERCURE 69800000.f
#define DISTANCE_APHELION_VENUS 108900000.f
#define DISTANCE_APHELION_TERRE 152100000.f
#define DISTANCE_APHELION_MARS 249300000.f
#define DISTANCE_APHELION_JUPITER 816400000.f
#define DISTANCE_APHELION_SATURNE 1506500000.f
#define DISTANCE_APHELION_URANUS 3001400000.f
#define DISTANCE_APHELION_NEPTUNE 4558900000.f
#define DISTANCE_APHELION_PLUTON 7375900000.f
// distance des satélites
#define DISTANCE_APHELION_MOON 406400.f
// mars
#define DISTANCE_APHELION_PHOBOS 9378.f
#define DISTANCE_APHELION_DEIMOS 23459.f
// jupiter
#define DISTANCE_APHELION_CALISTO 1896000.f
#define DISTANCE_APHELION_GANYMEDE 1072000.4f
#define DISTANCE_APHELION_EUROPA 678000.f
#define DISTANCE_APHELION_IO 424000.f
// saturne
#define DISTANCE_APHELION_MIMAS 185520.f
#define DISTANCE_APHELION_ENCELADUS 238020.f
#define DISTANCE_APHELION_TETHYS 294660.f
#define DISTANCE_APHELION_DIONE 294660.f
#define DISTANCE_APHELION_RHEA 527040.f
#define DISTANCE_APHELION_TITAN 1258000.f
#define DISTANCE_APHELION_HYPERION 1500930.f
#define DISTANCE_APHELION_IAPETUS 3560850.f
// uranus
#define DISTANCE_APHELION_ARIEL 190900.f
#define DISTANCE_APHELION_UMBRIEL 266000.f
#define DISTANCE_APHELION_TITANIA 436300.f
#define DISTANCE_APHELION_OBERON 583500.f
#define DISTANCE_APHELION_MIRANDA 129900.f
// neptune
#define DISTANCE_APHELION_TRITON 354760.f
#define DISTANCE_APHELION_NERIEDE 5513400.f
// pluton
#define DISTANCE_APHELION_CHARON 19596.f

#define COEF_DISTANCE_APHELION_MERCURE (DISTANCE_APHELION_MERCURE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_VENUS (DISTANCE_APHELION_VENUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_TERRE (DISTANCE_APHELION_TERRE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_MARS (DISTANCE_APHELION_MARS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_JUPITER (DISTANCE_APHELION_JUPITER / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_SATURNE (DISTANCE_APHELION_SATURNE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_URANUS (DISTANCE_APHELION_URANUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_NEPTUNE (DISTANCE_APHELION_NEPTUNE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_PLUTON (DISTANCE_APHELION_PLUTON / DISTANCE_SUN) / COEF_DISTANCE
// distance_APHELION des satélites
#define COEF_DISTANCE_APHELION_MOON (DISTANCE_APHELION_MOON / DISTANCE_SUN) / COEF_DISTANCE
// mars
#define COEF_DISTANCE_APHELION_PHOBOS (DISTANCE_APHELION_PHOBOS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_DEIMOS (DISTANCE_APHELION_DEIMOS / DISTANCE_SUN) / COEF_DISTANCE
// jupiter
#define COEF_DISTANCE_APHELION_CALISTO (DISTANCE_APHELION_CALISTO / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_GANYMEDE (DISTANCE_APHELION_GANYMEDE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_EUROPA (DISTANCE_APHELION_EUROPA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_IO (DISTANCE_APHELION_IO / DISTANCE_SUN) / COEF_DISTANCE
// saturne
#define COEF_DISTANCE_APHELION_MIMAS (DISTANCE_APHELION_MIMAS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_ENCELADUS (DISTANCE_APHELION_ENCELADUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_TETHYS (DISTANCE_APHELION_TETHYS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_DIONE (DISTANCE_APHELION_DIONE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_RHEA (DISTANCE_APHELION_RHEA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_TITAN (DISTANCE_APHELION_TITAN / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_HYPERION (DISTANCE_APHELION_HYPERION / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_IAPETUS (DISTANCE_APHELION_IAPETUS / DISTANCE_SUN) / COEF_DISTANCE
// uranus
#define COEF_DISTANCE_APHELION_ARIEL (DISTANCE_APHELION_ARIEL / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_UMBRIEL (DISTANCE_APHELION_UMBRIEL / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_TITANIA (DISTANCE_APHELION_TITANIA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_OBERON (DISTANCE_APHELION_OBERON / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_MIRANDA (DISTANCE_APHELION_MIRANDA / DISTANCE_SUN) / COEF_DISTANCE
// neptune
#define COEF_DISTANCE_APHELION_TRITON (DISTANCE_APHELION_TRITON / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_APHELION_NERIEDE (DISTANCE_APHELION_NERIEDE / DISTANCE_SUN) / COEF_DISTANCE
// pluton
#define COEF_DISTANCE_APHELION_CHARON (DISTANCE_APHELION_CHARON / DISTANCE_SUN) / COEF_DISTANCE

// saturne rings
# define DISTANCE_RADIUS_SATURNE_RING (COEF_DIAMETRE_SATURNE * 3.56)
# define DISTANCE_RADIUS_URANUS_RING (COEF_DIAMETRE_URANUS * 8)

const std::vector<std::string> planetsName = {"SUN","MERCURE","VENUS","TERRE","MARS","JUPITER","SATURNE","URANUS","NEPTUNE","PLUTON"};
