//
// Created by Antonin Jean on 29/12/2023.
//
#pragma once

#include "../shared/libs.hpp"
#include "../shared/utils.hpp"
#include <glimac/Sphere.hpp>
#include <iostream>
#include <cassert>

#define COEF_DIAMETRE 7
#define COEF_DISTANCE 30
#define DEFAULT_VALUE 1

// diametre des planetes
#define DIAMETRE_SUN 1400000.f
#define DIAMETRE_MERCURE 4879.f
#define DIAMETRE_VENUS 12104.f
#define DIAMETRE_TERRE 12756.f
#define DIAMETRE_MARS 6792.f
#define DIAMETRE_JUPITER 142984.f
#define DIAMETRE_SATURNE 120536.f
#define DIAMETRE_URANUS 51118.f
#define DIAMETRE_NEPTUNE 49528.f
#define DIAMETRE_PLUTON 2376.f
// diametre des satelites
#define DIAMETRE_MOON 3475.f
// mars
#define DIAMETRE_PHOBOS 18.2f
#define DIAMETRE_DEIMOS 10.2f
// jupiter
#define DIAMETRE_CALISTO 4820.f
#define DIAMETRE_GANYMEDE 5262.4f
#define DIAMETRE_EUROPA 3121.6f
#define DIAMETRE_IO 3643.f
// saturne
#define DIAMETRE_MIMAS 416.f
#define DIAMETRE_ENCELADUS 514.f
#define DIAMETRE_TETHYS 1076.f
#define DIAMETRE_DIONE 1126.f
#define DIAMETRE_RHEA 1530.f
#define DIAMETRE_TITAN 5150.f
#define DIAMETRE_HYPERION 360.f
#define DIAMETRE_IAPETUS 1492.f
// uranus
#define DIAMETRE_ARIEL 1160.f
#define DIAMETRE_UMBRIEL 1169.4f
#define DIAMETRE_TITANIA 1577.8f
#define DIAMETRE_OBERON 1522.8f
#define DIAMETRE_MIRANDA 480.f
// neptune
#define DIAMETRE_TRITON 2706.8f
#define DIAMETRE_NERIEDE 340.f
// pluton
#define DIAMETRE_CHARON 1212.f

// distance des planetes
#define DISTANCE_SUN 1400000.f
#define DISTANCE_MERCURE 57900000.f
#define DISTANCE_VENUS 108200000.f
#define DISTANCE_TERRE 149600000.f
#define DISTANCE_MARS 228000000.f
#define DISTANCE_JUPITER 778500000.f
#define DISTANCE_SATURNE 1432000000.f
#define DISTANCE_URANUS 2867000000.f
#define DISTANCE_NEPTUNE 4515000000.f
#define DISTANCE_PLUTON 5906400000.f
// distance des satélites
#define DISTANCE_MOON 384400.f
// mars
#define DISTANCE_PHOBOS 9378.f
#define DISTANCE_DEIMOS 23459.f
// jupiter
#define DISTANCE_CALISTO 1882000.f
#define DISTANCE_GANYMEDE 1070400.4f
#define DISTANCE_EUROPA 671100.f
#define DISTANCE_IO 421800.f
// saturne
#define DISTANCE_MIMAS 185520.f
#define DISTANCE_ENCELADUS 238020.f
#define DISTANCE_TETHYS 294660.f
#define DISTANCE_DIONE 294660.f
#define DISTANCE_RHEA 527040.f
#define DISTANCE_TITAN 1221870.f
#define DISTANCE_HYPERION 1500930.f
#define DISTANCE_IAPETUS 3560850.f
// uranus
#define DISTANCE_ARIEL 190900.f
#define DISTANCE_UMBRIEL 266000.f
#define DISTANCE_TITANIA 436300.f
#define DISTANCE_OBERON 583500.f
#define DISTANCE_MIRANDA 129900.f
// neptune
#define DISTANCE_TRITON 354760.f
#define DISTANCE_NERIEDE 5513400.f
// pluton
#define DISTANCE_CHARON 19596.f


#define COEF_DIAMETRE_SUN 2
#define COEF_DIAMETRE_MERCURE (DIAMETRE_MERCURE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_VENUS (DIAMETRE_VENUS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TERRE (DIAMETRE_TERRE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_MARS (DIAMETRE_MARS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_JUPITER (DIAMETRE_JUPITER / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_SATURNE (DIAMETRE_SATURNE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_URANUS (DIAMETRE_URANUS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_NEPTUNE (DIAMETRE_NEPTUNE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_PLUTON (DIAMETRE_PLUTON / DIAMETRE_SUN) * COEF_DIAMETRE
// diametre des satelites
#define COEF_DIAMETRE_MOON (DIAMETRE_MOON / DIAMETRE_SUN) * COEF_DIAMETRE
// mars
#define COEF_DIAMETRE_PHOBOS (DIAMETRE_PHOBOS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_DEIMOS (DIAMETRE_DEIMOS / DIAMETRE_SUN) * COEF_DIAMETRE
// jupiter
#define COEF_DIAMETRE_CALISTO (DIAMETRE_CALISTO / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_GANYMEDE (DIAMETRE_GANYMEDE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_EUROPA (DIAMETRE_EUROPA / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_IO (DIAMETRE_IO / DIAMETRE_SUN) * COEF_DIAMETRE
// saturne
#define COEF_DIAMETRE_MIMAS (DIAMETRE_MIMAS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_ENCELADUS (DIAMETRE_ENCELADUS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TETHYS (DIAMETRE_TETHYS / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_DIONE (DIAMETRE_DIONE / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_RHEA (DIAMETRE_RHEA / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TITAN (DIAMETRE_TITAN / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_HYPERION (DIAMETRE_HYPERION / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_IAPETUS (DIAMETRE_IAPETUS / DIAMETRE_SUN) * COEF_DIAMETRE
// uranus
#define COEF_DIAMETRE_ARIEL (DIAMETRE_ARIEL / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_UMBRIEL (DIAMETRE_UMBRIEL / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_TITANIA (DIAMETRE_TITANIA / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_OBERON (DIAMETRE_OBERON / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_MIRANDA (DIAMETRE_MIRANDA / DIAMETRE_SUN) * COEF_DIAMETRE
// neptune
#define COEF_DIAMETRE_TRITON (DIAMETRE_TRITON / DIAMETRE_SUN) * COEF_DIAMETRE
#define COEF_DIAMETRE_NERIEDE (DIAMETRE_NERIEDE / DIAMETRE_SUN) * COEF_DIAMETRE
// pluton
#define COEF_DIAMETRE_CHARON (DIAMETRE_CHARON / DIAMETRE_SUN) * COEF_DIAMETRE

#define COEF_DISTANCE_MERCURE (DISTANCE_MERCURE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_VENUS (DISTANCE_VENUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_TERRE (DISTANCE_TERRE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_MARS (DISTANCE_MARS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_JUPITER (DISTANCE_JUPITER / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_SATURNE (DISTANCE_SATURNE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_URANUS (DISTANCE_URANUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_NEPTUNE (DISTANCE_NEPTUNE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_PLUTON (DISTANCE_PLUTON / DISTANCE_SUN) / COEF_DISTANCE
// distance des satélites
#define COEF_DISTANCE_MOON (DISTANCE_MOON / DISTANCE_SUN) / COEF_DISTANCE
// mars
#define COEF_DISTANCE_PHOBOS (DISTANCE_PHOBOS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_DEIMOS (DISTANCE_DEIMOS / DISTANCE_SUN) / COEF_DISTANCE
// jupiter
#define COEF_DISTANCE_CALISTO (DISTANCE_CALISTO / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_GANYMEDE (DISTANCE_GANYMEDE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_EUROPA (DISTANCE_EUROPA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_IO (DISTANCE_IO / DISTANCE_SUN) / COEF_DISTANCE
// saturne
#define COEF_DISTANCE_MIMAS (DISTANCE_MIMAS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_ENCELADUS (DISTANCE_ENCELADUS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_TETHYS (DISTANCE_TETHYS / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_DIONE (DISTANCE_DIONE / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_RHEA (DISTANCE_RHEA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_TITAN (DISTANCE_TITAN / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_HYPERION (DISTANCE_HYPERION / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_IAPETUS (DISTANCE_IAPETUS / DISTANCE_SUN) / COEF_DISTANCE
// uranus
#define COEF_DISTANCE_ARIEL (DISTANCE_ARIEL / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_UMBRIEL (DISTANCE_UMBRIEL / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_TITANIA (DISTANCE_TITANIA / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_OBERON (DISTANCE_OBERON / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_MIRANDA (DISTANCE_MIRANDA / DISTANCE_SUN) / COEF_DISTANCE
// neptune
#define COEF_DISTANCE_TRITON (DISTANCE_TRITON / DISTANCE_SUN) / COEF_DISTANCE
#define COEF_DISTANCE_NERIEDE (DISTANCE_NERIEDE / DISTANCE_SUN) / COEF_DISTANCE
// pluton
#define COEF_DISTANCE_CHARON (DISTANCE_CHARON / DISTANCE_SUN) / COEF_DISTANCE